### ISSUE TITLE
Different data statistics for YELP 2020

### ISSUE THREAD

**Issue by hujilin1229** [layer6ai-labs/HGCF#2]
Hi, 

Thanks for sharing the code for this work. Recently, I tried to realize your code, but when I download your code and dataset for YLEP 2020, I found different data statics of this dataset. This is the output from my screen. 

_saving adj_csr to ./data/yelp20/adj_csr.npz
time elapsed 1.5251s
num_users 71135, num_items 45063
adjacency matrix shape:  (116198, 116198)_

From your paper, the number of users is 91,174, which is different from the output of the code. So I would like to know whether there's something wrong with the dataset that you uploaded?

Kind Regards,
Jilin

**Comment by jianing-sun** [comment]
Thanks for your question. I think there was a typo on the stats table regarding YELP. # user should be 71135 as you've seen from the pkl file.
